services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    image: dusagame/restaurante-api:1.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/restaurante?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: appuser
      DB_PASS: apppass

  frontend:
    image: dusagame/restaurante-frontend:1.0
    ports:
      - "80:80"
    depends_on:
      - app
